apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-scrape-configs
  namespace: monitoring
data:
  prometheus-additional.yaml: |
    - job_name: 'nginx-metrics'
      metrics_path: /metrics
      static_configs:
        - targets: ['my-app.my-app-ns.svc.cluster.local:9113']
